services:
  - type: web
    name: hashnect-backend
    env: node
    rootDir: backend
    nodeVersion: 18.19.1
    buildCommand: |
      cd backend
      yarn install --frozen-lockfile
      yarn add typescript @types/node
      yarn build
    startCommand: cd backend && yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: JWT_SECRET
        sync: false 