services:
  - type: web
    name: hashnect-backend
    env: node
    rootDir: backend
    nodeVersion: 18.19.1
    buildCommand: |
      cd backend
      yarn install --frozen-lockfile
      yarn add @nestjs/common @nestjs/config @nestjs/core @nestjs/jwt @nestjs/passport @nestjs/platform-express @nestjs/swagger @prisma/client class-transformer class-validator passport passport-google-oauth20 passport-jwt prisma stripe
      yarn add -D @types/express @types/node @types/passport-google-oauth20 @types/passport-jwt typescript
      yarn prisma generate
      yarn build
    startCommand: cd backend && yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
      - key: JWT_SECRET
        sync: false 